-- Atualizacao da tecnica Sete Caminhos Mundanos
START TRANSACTION;

INSERT INTO `tecnica_amaldicoada` (`codigo`, `nome`, `descricao`, `tipo`, `hereditaria`, `requisitos`, `fonte`, `criadoEm`, `atualizadoEm`)
VALUES ('SETE_CAMINHOS_MUNDANOS', 'Sete Caminhos Mundanos', 'Roleta amaldiçoada que concede um dos Caminhos Mundanos durante a cena.', 'INATA', FALSE, CAST('{"roleta":"Ao ativar a técnica, o usuário recebe aleatoriamente 1 Caminho Mundano que permanece até o fim da cena.","primeiroUso":"Na primeira roleta da cena, o usuário pode excluir 1 caminho indesejado e duplicar 1 caminho desejado na roleta.","novoGiro":"Para roletar novamente, precisa esperar ao menos 1 rodada e pagar 2 EA e 2 PE.","trocaDeCaminho":"Sempre remove o caminho atualmente ativo antes do novo giro, podendo reintroduzir caminhos removidos ao alterar a duplicação.","estadoAtual":"Atualização atual contempla Belianorr, Indivar, Saadnar, Grandier, Moxtar e Vazark."}' AS JSON), 'SISTEMA_BASE', NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `tipo` = VALUES(`tipo`),
  `hereditaria` = VALUES(`hereditaria`),
  `requisitos` = VALUES(`requisitos`),
  `fonte` = VALUES(`fonte`),
  `atualizadoEm` = NOW();

SET @tecnicaId := (SELECT `id` FROM `tecnica_amaldicoada` WHERE `codigo` = 'SETE_CAMINHOS_MUNDANOS' LIMIT 1);

-- Limpa variacoes existentes dessas habilidades para recriar com a ordem correta
DELETE FROM `variacao_habilidade`
WHERE `habilidadeTecnicaId` IN (
  SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` IN ('INATA_SETE_CAMINHOS_ROLETA', 'INATA_SETE_BELIANORR_CORRENTES', 'INATA_SETE_BELIANORR_PERTURBACAO', 'INATA_SETE_BELIANORR_INEVITAVEL', 'INATA_SETE_BELIANORR_ATIVAR_MARCAS', 'INATA_SETE_INDIVAR_APROPRIACAO', 'INATA_SETE_INDIVAR_EU_TAMBEM', 'INATA_SETE_SAADNAR_ORBES', 'INATA_SETE_SAADNAR_CONSUMIR', 'INATA_SETE_SAADNAR_DEVORAR', 'INATA_SETE_SAADNAR_INGERIR', 'INATA_SETE_GRANDIER_POSSE', 'INATA_SETE_GRANDIER_APEGO', 'INATA_SETE_GRANDIER_CIRCULO', 'INATA_SETE_MOXTAR_PARTES', 'INATA_SETE_MOXTAR_AUREOLA', 'INATA_SETE_MOXTAR_ASAS', 'INATA_SETE_MOXTAR_CAUDA', 'INATA_SETE_VAZARK_PATAS', 'INATA_SETE_VAZARK_VINCULO', 'INATA_SETE_VAZARK_RUGIDO', 'INATA_SETE_VAZARK_DESAFIO')
);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_CAMINHOS_ROLETA', 'Roleta dos Caminhos', 'Gira a roleta amaldiçoada e define qual Caminho Mundano ficará ativo na cena.', NULL, 'ACAO_PADRAO', NULL, 'Pessoal', 'Você', 'Cena', NULL, NULL, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Ativa aleatoriamente 1 Caminho Mundano. O primeiro giro da cena pode excluir 1 caminho e duplicar outro. Para girar novamente, aguarde 1 rodada e pague 2 EA e 2 PE, removendo obrigatoriamente o caminho atual da roleta.', 10, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_CAMINHOS_ROLETA' LIMIT 1), 'Belianorr (Preguiça)', 'Correntes amaldiçoadas revestem o corpo do usuário e drenam a determinação do alvo.', FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Personalidade: sonolento e sem determinação. Correntes: espaço 1, 1d8 x2 de impacto contra alvos comuns e exorciza maldições. Concede +2 em testes para derrubar e desarmar enquanto este Caminho estiver ativo.', CAST('{"caminhoAtivo":"BELIANORR"}' AS JSON), 10, NOW(), NOW());

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_CAMINHOS_ROLETA' LIMIT 1), 'Indivar (Inveja)', 'Um terceiro olho se abre e busca apropriar-se de aspectos admiráveis de outras criaturas.', FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Desejo de Indivar: rouba fragmentos da identidade amaldiçoada em vez de copiar técnicas. Olhar de Indivar: percebe instintivamente o aspecto mais admirável de cada alvo observado.', CAST('{"caminhoAtivo":"INDIVAR"}' AS JSON), 20, NOW(), NOW());

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_CAMINHOS_ROLETA' LIMIT 1), 'Saadnar (Gula)', 'Seis orbes negros orbitam o usuário e representam a fome de devorar energia, condições e existência.', FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ao entrar no Caminho, recebe 6 orbes. Sem orbes, o usuário sai de Saadnar. Orbes da Fome: 1d4 x2 de impacto e exorciza maldições.', CAST('{"caminhoAtivo":"SAADNAR"}' AS JSON), 30, NOW(), NOW());

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_CAMINHOS_ROLETA' LIMIT 1), 'Grandier (Avareza)', 'Uma algema dourada prende o usuário ao Crânio do Contador e impõe as leis da posse.', FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Crânio do Contador: cajado amaldiçoado feito de crânio humano e coluna vertebral, adornado com ouro e preso ao pulso esquerdo do usuário.', CAST('{"caminhoAtivo":"GRANDIER"}' AS JSON), 40, NOW(), NOW());

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_CAMINHOS_ROLETA' LIMIT 1), 'Moxtar (Orgulho)', 'Fragmentos do corpo divino de Moxtar descem sobre o usuário e alimentam sua arrogância.', FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Enquanto Moxtar estiver ativo, o usuário tende a recusar ajuda, ignorar conselhos e correr riscos para provar superioridade.', CAST('{"caminhoAtivo":"MOXTAR"}' AS JSON), 50, NOW(), NOW());

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_CAMINHOS_ROLETA' LIMIT 1), 'Vazark (Raiva)', 'O usuário é invadido pela mente livre e insana de Vazark, trocando razão por impulso destrutivo.', FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Patas de Vazark: espaço 2, 3d6 + Força de dano cortante, crítico 20 x3. Enquanto ativo, o usuário deve atacar um alvo em sua rodada sempre que possível.', CAST('{"caminhoAtivo":"VAZARK"}' AS JSON), 60, NOW(), NOW());

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_BELIANORR_CORRENTES', 'Correntes de Belianorr', 'Usa as correntes de Belianorr como arma amaldiçoada para ataque corpo a corpo.', CAST('{"caminhoAtivo":"BELIANORR"}' AS JSON), 'AO_ATACAR', NULL, 'Corpo a corpo', '1 ser', 'Instantâneo', NULL, NULL, 0, 0, NULL, NULL, CAST('["Luta"]' AS JSON), 20, 2, NULL, NULL, CAST('[{"quantidade":1,"dado":"d8","tipo":"IMPACTO"}]' AS JSON), FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Requer Belianorr ativo. As correntes exorcizam maldições e concedem +2 em testes para derrubar e desarmar.', 20, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_BELIANORR_PERTURBACAO', 'Belianorr - Perturbação', 'Cada golpe acertado com as correntes deixa uma Marca que sela a força de vontade do alvo.', CAST('{"caminhoAtivo":"BELIANORR"}' AS JSON), 'AO_ATACAR', NULL, 'Corpo a corpo', '1 ser', 'Instantâneo', 'Vontade', NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Cada golpe corpo a corpo que acertar com as correntes deixa 1 Marca na parte atingida. Cada Marca isolada não causa efeito por si só, mas pode ser ativada depois. O alvo pode gastar 1 ação padrão para fazer teste de Vontade e remover as Marcas.', 30, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_BELIANORR_INEVITAVEL', 'Belianorr - Inevitável', 'Puxa até você um alvo marcado pelas correntes de Belianorr.', CAST('{"caminhoAtivo":"BELIANORR","marcasMinimas":1}' AS JSON), 'ACAO_MOVIMENTO', NULL, 'Curto', '1 ser', 'Instantâneo', 'Fortitude anula', NULL, 0, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Escolhe 1 ser que carregue ao menos 1 Marca e o puxa até você. Cada Marca no alvo concede +2 na DT desta habilidade.', 40, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_BELIANORR_ATIVAR_MARCAS', 'Belianorr - Ativar Marcas', 'Ativa as Marcas acumuladas para impor lentidão, fraqueza ou debilitação.', CAST('{"caminhoAtivo":"BELIANORR","consomeMarcas":true}' AS JSON), 'ACAO_MOVIMENTO', NULL, 'Curto', '1 ser', 'Instantâneo', 'Fortitude', NULL, 0, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Custa 1 EA por Marca ativada. 1 Marca: Fortitude DT de técnicas +4; falha deixa LENTO. 2 Marcas: Fortitude DT de técnicas +6; falha deixa LENTO e FRACO, sucesso deixa apenas LENTO. 3 Marcas: Fortitude DT de técnicas +8; falha deixa DEBILITADO, sucesso deixa FRACO.', 50, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_INDIVAR_APROPRIACAO', 'Indivar - Apropriação Profana', 'Copia ou rouba propriedades amaldiçoadas de um alvo observado.', CAST('{"caminhoAtivo":"INDIVAR"}' AS JSON), 'ACAO_MOVIMENTO', NULL, 'Curto', '1 ser', 'Cena', 'Vontade evita', NULL, 2, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Escolha 1 propriedade do alvo: 1 bônus de perícia, 1 tipo de resistência, 1 tipo de dano, 1 valor de atributo ou 1 grau de aprimoramento conhecido. Vontade evita a cópia.', 60, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_INDIVAR_APROPRIACAO' LIMIT 1), 'Superior', 'Copia mais propriedades do mesmo alvo.', FALSE, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Consegue copiar 1 + grau de aprimoramento em Técnica Amaldiçoada propriedades do alvo.', NULL, 10, NOW(), NOW());

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_INDIVAR_APROPRIACAO' LIMIT 1), 'Máxima', 'Rouba a propriedade em vez de apenas copiá-la.', FALSE, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Rouba 1 única propriedade do alvo até o fim da cena, impedindo o alvo de usá-la enquanto durar o efeito.', NULL, 20, NOW(), NOW());

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_INDIVAR_EU_TAMBEM', 'Indivar - Eu Também Consigo', 'Refaz um teste após ver outra criatura ter sucesso em situação equivalente.', CAST('{"caminhoAtivo":"INDIVAR"}' AS JSON), 'REACAO', NULL, 'Visão do usuário', 'Você', 'Instantâneo', NULL, NULL, 0, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Quando outra pessoa ou criatura realiza o mesmo teste que você na mesma rodada e obtém sucesso, você pode refazer o teste imediatamente. Não vale para testes contra, salvo pela variação Superior.', 70, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_INDIVAR_EU_TAMBEM' LIMIT 1), 'Superior', 'Expande a apropriação para testes contra.', FALSE, 1, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Também pode ser usada em testes contra.', NULL, 10, NOW(), NOW());

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_SAADNAR_ORBES', 'Saadnar - Orbes da Fome', 'Dispara um orbe básico de Saadnar contra um alvo próximo.', CAST('{"caminhoAtivo":"SAADNAR","recurso":"ORBES"}' AS JSON), 'AO_ATACAR', NULL, 'Curto', '1 ser', 'Instantâneo', NULL, NULL, 0, 0, NULL, NULL, CAST('["Pontaria com Jujutsu"]' AS JSON), 20, 2, NULL, NULL, CAST('[{"quantidade":1,"dado":"d4","tipo":"IMPACTO"}]' AS JSON), FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Requer Saadnar ativo e ao menos 1 orbe disponível. Os orbes exorcizam maldições.', 80, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_SAADNAR_CONSUMIR', 'Saadnar - Consumir', 'Sacrifica 1 orbe para absorver energia amaldiçoada de um ataque.', CAST('{"caminhoAtivo":"SAADNAR","recurso":"ORBES"}' AS JSON), 'REACAO', NULL, 'Pessoal', 'Você', 'Instantâneo', NULL, NULL, 2, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Gasta 1 orbe para transformar até 20 do dano recebido em RD contra aquele ataque. Pode acumular +5 RD por EA extra gasto, até o limite do seu grau em Técnica Amaldiçoada.', 90, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_SAADNAR_CONSUMIR' LIMIT 1), 'Absorver Ambiente', 'Converte 1 orbe em vida temporária até o fim da cena.', TRUE, 2, 4, NULL, NULL, 'ACAO_PADRAO', NULL, 'Pessoal', 'Você', 'Instantâneo', NULL, NULL, NULL, NULL, NULL, NULL, CAST('[{"quantidade":2,"dado":"d8","tipo":"ENERGIA_AMALDICOADA"}]' AS JSON), NULL, NULL, NULL, NULL, NULL, NULL, 'Em vez de RD, recebe 2d8 de vida temporária até o fim da cena. Pode acumular +1d8 de vida temporária por EA extra gasto, até o limite do grau em Técnica Amaldiçoada.', NULL, 10, NOW(), NOW());

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_SAADNAR_DEVORAR', 'Saadnar - Devorar', 'Dispara 1 ou mais orbes em direção a um alvo para causar dano.', CAST('{"caminhoAtivo":"SAADNAR","recurso":"ORBES"}' AS JSON), 'ACAO_PADRAO', NULL, 'Curto', '1 ser', 'Instantâneo', NULL, NULL, 0, 2, NULL, NULL, CAST('["Pontaria com Jujutsu"]' AS JSON), 20, 2, NULL, NULL, CAST('[{"quantidade":1,"dado":"d4","tipo":"IMPACTO"}]' AS JSON), FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Controla 1 orbe e o dispara contra o alvo; o orbe some após atingir. Pode acumular orbes para cada +1 EA gasto adicional.', 100, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_SAADNAR_INGERIR', 'Saadnar - Ingerir', 'Usa 1 orbe para consumir uma condição negativa de um alvo.', CAST('{"caminhoAtivo":"SAADNAR","recurso":"ORBES"}' AS JSON), 'ACAO_PADRAO', NULL, 'Curto', '1 ser', 'Instantâneo', NULL, NULL, 0, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Gasta 1 orbe para que ele viaje até o alvo e consuma 1 condição negativa, exceto MORRENDO, MACHUCADO, LOUCO ou ENLOUQUECENDO. Pode acumular orbes para cada +1 EA extra gasto.', 110, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_GRANDIER_POSSE', 'Grandier - Posse', 'Reafirma o direito absoluto do usuário sobre um item que empunha.', CAST('{"caminhoAtivo":"GRANDIER"}' AS JSON), 'ACAO_PADRAO', NULL, 'Pessoal', 'Você', 'Instantâneo', NULL, NULL, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Escolha 1 item empunhado. Você fica imune à manobra desarmar com esse item e recebe +2 em testes ligados ao uso dele. Ex.: armas concedem +2 em Luta.', 120, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_GRANDIER_POSSE' LIMIT 1), 'Superior', 'Transforma a familiaridade com o item em superioridade técnica.', FALSE, NULL, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Além dos efeitos base, recebe +1 dado em testes usando o item escolhido.', NULL, 10, NOW(), NOW());

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_GRANDIER_APEGO', 'Grandier - Apego', 'Materializa um objeto de avareza e força o alvo a mantê-lo nas mãos.', CAST('{"caminhoAtivo":"GRANDIER"}' AS JSON), 'ACAO_PADRAO', NULL, 'Curto', '1 ser', 'Instantâneo', 'Vontade anula', NULL, 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Materializa um objeto de avareza que ocupa as duas mãos do alvo e o obriga a mantê-lo por 1d2+1 rodadas.', 130, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_GRANDIER_APEGO' LIMIT 1), 'Superior', 'Faz o alvo apegar-se ao objeto por ainda mais tempo.', FALSE, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Some o valor do Grau de Aprimoramento em Técnica Amaldiçoada ao número de rodadas do efeito.', NULL, 10, NOW(), NOW());

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_GRANDIER_CIRCULO', 'Grandier - Círculo do Penhor', 'Crava o cajado no solo e transforma a área em uma penhora amaldiçoada.', CAST('{"caminhoAtivo":"GRANDIER","grauMinimo":{"codigo":"TECNICA_BARREIRA","valor":1}}' AS JSON), 'ACAO_PADRAO', NULL, 'Curto', 'Aliados e inimigos na área', 'Sustentado', 'Vontade anula (apenas inimigos)', NULL, 2, 3, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Requer Grau de Aprimoramento em Técnica de Barreira 1. Enquanto sustentar, o usuário não pode sair do ponto inicial. Aliados reduzem em 1 EA o custo de técnicas amaldiçoadas (mínimo 1). Inimigos ficam ALQUEBRADOS.', 140, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_MOXTAR_PARTES', 'Moxtar - Partes do Divino', 'Recebe partes sagradas e grotescas do corpo de Moxtar.', CAST('{"caminhoAtivo":"MOXTAR"}' AS JSON), 'ACAO_PADRAO', NULL, 'Pessoal', 'Você', 'Sustentado', NULL, NULL, 2, 3, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Escolha 1 parte de Moxtar para manifestar até o fim da cena: Auréola de Carne, Asas de Carne ou Cauda de Moxtar. Esta habilidade pode ser usada novamente até que todas as partes tenham sido manifestadas.', 150, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_MOXTAR_PARTES' LIMIT 1), 'Superior', 'Sustenta duas partes simultaneamente.', FALSE, NULL, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Pode manter até 2 partes de Moxtar ativas ao mesmo tempo.', NULL, 10, NOW(), NOW());

INSERT INTO `variacao_habilidade` (`habilidadeTecnicaId`, `nome`, `descricao`, `substituiCustos`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeitoAdicional`, `requisitos`, `ordem`, `criadoEm`, `atualizadoEm`) VALUES ((SELECT `id` FROM `habilidade_tecnica` WHERE `codigo` = 'INATA_SETE_MOXTAR_PARTES' LIMIT 1), 'Máxima', 'Manifesta as três partes do divino de uma só vez.', FALSE, NULL, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 'Ativa as três partes instantaneamente.', NULL, 20, NOW(), NOW());

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_MOXTAR_AUREOLA', 'Moxtar - Auréola de Carne', 'Desafia o alvo em uma prova escolhida por ele e converte a vitória em submissão ou devoção.', CAST('{"caminhoAtivo":"MOXTAR","parteAtiva":"AUREOLA_DE_CARNE"}' AS JSON), 'ACAO_PADRAO', NULL, 'Curto', '1 ser', 'Instantâneo', 'Varia', NULL, 1, 2, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Requer a parte Auréola de Carne ativa. O alvo escolhe a atividade ou desafio. Se vencer, escolha 1 benefício: Devoção Roubada (2d6 PE e EA temporários enquanto sustentar a parte), Orgulho Quebrado (+2 contra o alvo e você vai para frente dele na iniciativa) ou Convicção Superior (alvo fica CAÍDO, perde a próxima ação de movimento e sofre -2 contra você enquanto sustentar a parte).', 160, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_MOXTAR_ASAS', 'Moxtar - Asas de Carne', 'As asas deformadas de Moxtar defendem o usuário e sustentam seu voo.', CAST('{"caminhoAtivo":"MOXTAR","parteAtiva":"ASAS_DE_CARNE"}' AS JSON), 'REACAO', NULL, 'Pessoal', 'Você', 'Instantâneo', NULL, NULL, 2, 0, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Requer a parte Asas de Carne ativa. Enquanto a parte estiver ativa, você recebe deslocamento de voo. As asas têm 30 PV e 5 RD. Ao usar esta habilidade, recebe RD 10 contra o ataque, mas o dano absorvido é transferido para as asas sem aplicar essa RD a elas.', 170, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_MOXTAR_CAUDA', 'Moxtar - Cauda de Moxtar', 'Usa a cauda divina para golpear em conjunto com o ataque principal.', CAST('{"caminhoAtivo":"MOXTAR","parteAtiva":"CAUDA_DE_MOXTAR"}' AS JSON), 'AO_ATACAR', NULL, 'Corpo a corpo', '1 ser', 'Instantâneo', NULL, NULL, 2, 0, NULL, NULL, CAST('["Luta"]' AS JSON), 20, 2, NULL, NULL, CAST('[{"quantidade":1,"dado":"d6","tipo":"IMPACTO"}]' AS JSON), FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Requer a parte Cauda de Moxtar ativa. A cauda funciona como mão extra, concede +4 em manobras de combate e +2 em Acrobacia. Ao usar a habilidade, o golpe causa 1d6 + Força de dano de impacto e pode receber revestimento de energia amaldiçoada.', 180, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_VAZARK_PATAS', 'Vazark - Patas da Besta', 'As enormes manoplas de carne viva de Vazark dilaceram o alvo em combate direto.', CAST('{"caminhoAtivo":"VAZARK"}' AS JSON), 'AO_ATACAR', NULL, 'Corpo a corpo', '1 ser', 'Instantâneo', NULL, NULL, 0, 0, NULL, NULL, CAST('["Luta"]' AS JSON), 20, 3, NULL, NULL, CAST('[{"quantidade":3,"dado":"d6","tipo":"CORTANTE"}]' AS JSON), FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Requer Vazark ativo. As patas ocupam espaço 2 e substituem as mãos enquanto este Caminho estiver ativo.', 190, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_VAZARK_VINCULO', 'Vazark - Vínculo da Besta', 'Abraça a ferocidade de Vazark para lutar sem contenção.', CAST('{"caminhoAtivo":"VAZARK"}' AS JSON), 'ACAO_PADRAO', NULL, 'Pessoal', 'Você', 'Sustentado', NULL, NULL, 1, 2, 1, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Enquanto ativo, recebe +2 em ataques corpo a corpo, +2 em rolagens de dano corpo a corpo e resistência 5 contra Balístico, Corte, Impacto e Perfuração.', 200, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_VAZARK_RUGIDO', 'Vazark - Rugido de Vazark', 'Libera um rugido que inflama a raiva de todos que o escutam.', CAST('{"caminhoAtivo":"VAZARK"}' AS JSON), 'ACAO_PADRAO', NULL, 'Médio', 'Seres ao alcance', '1d3 rodadas', 'Vontade anula', NULL, 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Quem falhar recebe +5 em testes de Luta e Pontaria, mas sofre -5 na Defesa enquanto durar o efeito.', 210, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

INSERT INTO `habilidade_tecnica` (`tecnicaId`, `codigo`, `nome`, `descricao`, `requisitos`, `execucao`, `area`, `alcance`, `alvo`, `duracao`, `resistencia`, `dtResistencia`, `custoPE`, `custoEA`, `custoSustentacaoEA`, `custoSustentacaoPE`, `testesExigidos`, `criticoValor`, `criticoMultiplicador`, `danoFlat`, `danoFlatTipo`, `dadosDano`, `escalonaPorGrau`, `grauTipoGrauCodigo`, `escalonamentoCustoEA`, `escalonamentoCustoPE`, `escalonamentoTipo`, `escalonamentoEfeito`, `escalonamentoDano`, `efeito`, `ordem`, `criadoEm`, `atualizadoEm`)
VALUES (@tecnicaId, 'INATA_SETE_VAZARK_DESAFIO', 'Vazark - Desafio Bestial', 'Instiga 1 alvo a entrar num confronto direto e brutal com você.', CAST('{"caminhoAtivo":"VAZARK"}' AS JSON), 'AO_ATACAR', NULL, 'Curto', '1 ser', '1d3 rodadas', 'Vontade', NULL, 1, 3, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, FALSE, NULL, 0, 0, 'OUTRO', NULL, NULL, 'Você e o alvo devem usar tudo que têm para entrar em alcance corpo a corpo e se atacar mutuamente. A única reação especial permitida entre vocês é Contra-ataque. Ambos recebem +1 dado de dano e +5 nos testes de ataque um contra o outro, inclusive no primeiro ataque.', 220, NOW(), NOW())
ON DUPLICATE KEY UPDATE
  `tecnicaId` = VALUES(`tecnicaId`),
  `nome` = VALUES(`nome`),
  `descricao` = VALUES(`descricao`),
  `requisitos` = VALUES(`requisitos`),
  `execucao` = VALUES(`execucao`),
  `area` = VALUES(`area`),
  `alcance` = VALUES(`alcance`),
  `alvo` = VALUES(`alvo`),
  `duracao` = VALUES(`duracao`),
  `resistencia` = VALUES(`resistencia`),
  `dtResistencia` = VALUES(`dtResistencia`),
  `custoPE` = VALUES(`custoPE`),
  `custoEA` = VALUES(`custoEA`),
  `custoSustentacaoEA` = VALUES(`custoSustentacaoEA`),
  `custoSustentacaoPE` = VALUES(`custoSustentacaoPE`),
  `testesExigidos` = VALUES(`testesExigidos`),
  `criticoValor` = VALUES(`criticoValor`),
  `criticoMultiplicador` = VALUES(`criticoMultiplicador`),
  `danoFlat` = VALUES(`danoFlat`),
  `danoFlatTipo` = VALUES(`danoFlatTipo`),
  `dadosDano` = VALUES(`dadosDano`),
  `escalonaPorGrau` = VALUES(`escalonaPorGrau`),
  `grauTipoGrauCodigo` = VALUES(`grauTipoGrauCodigo`),
  `escalonamentoCustoEA` = VALUES(`escalonamentoCustoEA`),
  `escalonamentoCustoPE` = VALUES(`escalonamentoCustoPE`),
  `escalonamentoTipo` = VALUES(`escalonamentoTipo`),
  `escalonamentoEfeito` = VALUES(`escalonamentoEfeito`),
  `escalonamentoDano` = VALUES(`escalonamentoDano`),
  `efeito` = VALUES(`efeito`),
  `ordem` = VALUES(`ordem`),
  `atualizadoEm` = VALUES(`atualizadoEm`);

-- Opcional: remocao de habilidades antigas que nao pertencem mais a esta versao.
-- DELETE FROM `habilidade_tecnica`
-- WHERE `tecnicaId` = @tecnicaId
--   AND `codigo` NOT IN ('INATA_SETE_CAMINHOS_ROLETA', 'INATA_SETE_BELIANORR_CORRENTES', 'INATA_SETE_BELIANORR_PERTURBACAO', 'INATA_SETE_BELIANORR_INEVITAVEL', 'INATA_SETE_BELIANORR_ATIVAR_MARCAS', 'INATA_SETE_INDIVAR_APROPRIACAO', 'INATA_SETE_INDIVAR_EU_TAMBEM', 'INATA_SETE_SAADNAR_ORBES', 'INATA_SETE_SAADNAR_CONSUMIR', 'INATA_SETE_SAADNAR_DEVORAR', 'INATA_SETE_SAADNAR_INGERIR', 'INATA_SETE_GRANDIER_POSSE', 'INATA_SETE_GRANDIER_APEGO', 'INATA_SETE_GRANDIER_CIRCULO', 'INATA_SETE_MOXTAR_PARTES', 'INATA_SETE_MOXTAR_AUREOLA', 'INATA_SETE_MOXTAR_ASAS', 'INATA_SETE_MOXTAR_CAUDA', 'INATA_SETE_VAZARK_PATAS', 'INATA_SETE_VAZARK_VINCULO', 'INATA_SETE_VAZARK_RUGIDO', 'INATA_SETE_VAZARK_DESAFIO');

COMMIT;