import type { WorldInstitution, WorldPlace } from './world.types';

export const WORLD_PLACES: WorldPlace[] = [
  {
    id: 'japao',
    kind: 'LUGAR',
    escala: 'REGIAO',
    nome: 'Japão',
    lat: 36.2048,
    lng: 138.2529,
    resumo: 'Centro de maior atividade jujutsu catalogada no cenário.',
    descricaoCurta:
      'O arquipélago concentra escolas, clãs, barreiras e zonas de contenção que sustentam a sociedade jujutsu moderna.',
    tags: ['jujutsu', 'arquivamento', 'barreiras'],
    status: 'ATIVA',
    nivelDeSigilo: 'RESTRITO',
    subtipo: 'Arquipélago',
    displayPriority: 1,
  },
  {
    id: 'imperio-kakyn',
    kind: 'LUGAR',
    escala: 'REGIAO',
    nome: 'Império de Kakyn',
    lat: 13.1,
    lng: 73.8,
    resumo: 'Região fictícia e sobrenatural projetada no atlas do cenário.',
    descricaoCurta:
      'Kakyn é tratado como um território político oculto, posicionado de forma narrativa no Oceano Índico, próximo à Índia, sem equivalência cartográfica real.',
    tags: ['kakyn', 'região fictícia', 'sobrenatural'],
    status: 'OCULTA',
    nivelDeSigilo: 'OCULTO',
    ficticio: true,
    subtipo: 'Império oculto',
    displayPriority: 2,
    notaCartografica:
      'Projeção fictícia do cenário. A posição indica referência narrativa e não representa geografia real.',
  },
  {
    id: 'cidadela',
    kind: 'LUGAR',
    escala: 'ZONA',
    nome: 'A Cidadela',
    lat: 35.735,
    lng: 139.214,
    resumo: 'Enclave fortificado de arquivo, logística e administração jujutsu.',
    descricaoCurta:
      'Instalada nas redondezas de Tokyo, em uma região menos densa e mais verticalizada, a Cidadela funciona como eixo de custódia, trânsito e controle operacional.',
    tags: ['cidadela', 'arquivo', 'distritos'],
    status: 'RESTRITA',
    nivelDeSigilo: 'CONFIDENCIAL',
    parentId: 'japao',
    subtipo: 'Enclave cartográfico',
    displayPriority: 3,
    mapaInterno: {
      src: '/images/world/cidadela-map.png',
      alt: 'Mapa interno da Cidadela com distritos industrial, comercial e de entretenimento',
    },
    notaCartografica:
      'A marcação representa uma projeção operacional aproximada nos arredores de Tokyo.',
  },
  {
    id: 'cidadela-distrito-industrial',
    kind: 'LUGAR',
    escala: 'SETOR',
    nome: 'Distrito Industrial',
    lat: 35.742,
    lng: 139.202,
    resumo: 'Zona fabril, logística, infraestrutura e depósitos da Cidadela.',
    descricaoCurta:
      'Concentra oficinas, galpões, rotas de carga, manutenção de equipamentos e áreas de descarte controlado.',
    tags: ['cidadela', 'industrial', 'logística'],
    status: 'RESTRITA',
    nivelDeSigilo: 'CONFIDENCIAL',
    parentId: 'cidadela',
    zoomMin: 'DETALHE',
    subtipo: 'Distrito',
    corVisual: 'cinza',
    displayPriority: 20,
  },
  {
    id: 'cidadela-distrito-comercial',
    kind: 'LUGAR',
    escala: 'SETOR',
    nome: 'Distrito Comercial',
    lat: 35.734,
    lng: 139.218,
    resumo: 'Centro de comércio, escritórios, serviços e circulação da Cidadela.',
    descricaoCurta:
      'Reúne corredores de negociação, balcões administrativos, hospedarias discretas e serviços autorizados.',
    tags: ['cidadela', 'comércio', 'serviços'],
    status: 'RESTRITA',
    nivelDeSigilo: 'CONFIDENCIAL',
    parentId: 'cidadela',
    zoomMin: 'DETALHE',
    subtipo: 'Distrito',
    corVisual: 'roxo',
    displayPriority: 21,
  },
  {
    id: 'cidadela-distrito-entretenimento',
    kind: 'LUGAR',
    escala: 'SETOR',
    nome: 'Distrito do Entretenimento',
    lat: 35.727,
    lng: 139.229,
    resumo: 'Vida noturna, casas de espetáculo, bares e zonas de alto fluxo social.',
    descricaoCurta:
      'Área de circulação intensa onde encontros informais, rumores e operações veladas se misturam sob vigilância constante.',
    tags: ['cidadela', 'entretenimento', 'vida noturna'],
    status: 'RESTRITA',
    nivelDeSigilo: 'CONFIDENCIAL',
    parentId: 'cidadela',
    zoomMin: 'DETALHE',
    subtipo: 'Distrito',
    corVisual: 'coral',
    displayPriority: 22,
  },
];

export const WORLD_INSTITUTIONS: WorldInstitution[] = [
  {
    id: 'escola-tecnica-tokyo',
    kind: 'INSTITUICAO',
    parentId: 'japao',
    nome: 'Escola Técnica Jujutsu de Tokyo',
    lat: 35.6895,
    lng: 139.6917,
    resumo: 'Arquivo central de formação, missão e contenção de incidentes.',
    descricaoCurta:
      'A unidade de Tokyo concentra estudantes, instrutores e operações de resposta rápida contra ameaças amaldiçoadas no leste do Japão.',
    tags: ['escola', 'operações', 'tokyo'],
    status: 'ATIVA',
    nivelDeSigilo: 'RESTRITO',
    subtipo: 'Escola técnica',
    displayPriority: 10,
  },
  {
    id: 'escola-tecnica-kyoto',
    kind: 'INSTITUICAO',
    parentId: 'japao',
    nome: 'Escola Técnica Jujutsu de Kyoto',
    lat: 35.0116,
    lng: 135.7681,
    resumo: 'Polo tradicional de treinamento e custódia de registros antigos.',
    descricaoCurta:
      'A unidade de Kyoto preserva linhagens, técnicas e protocolos antigos, servindo como contraponto político e acadêmico a Tokyo.',
    tags: ['escola', 'tradição', 'kyoto'],
    status: 'ATIVA',
    nivelDeSigilo: 'RESTRITO',
    subtipo: 'Escola técnica',
    displayPriority: 11,
  },
  {
    id: 'instalacoes-cla-hasaba',
    kind: 'INSTITUICAO',
    parentId: 'japao',
    nome: 'Instalações do Clã Hasaba',
    lat: 35.772,
    lng: 139.112,
    resumo: 'Complexo de treinamento e custódia nas montanhas próximas a Tokyo.',
    descricaoCurta:
      'As instalações do Clã Hasaba aparecem no atlas como coordenada aproximada, suficiente para navegação narrativa sem expor detalhes internos.',
    tags: ['clã hasaba', 'montanha', 'instalações'],
    status: 'RESTRITA',
    nivelDeSigilo: 'CONFIDENCIAL',
    subtipo: 'Instalações de clã',
    displayPriority: 12,
    notaCartografica:
      'Coordenada aproximada em região montanhosa nos arredores de Tokyo.',
  },
];

export const WORLD_LOCATIONS = [...WORLD_PLACES, ...WORLD_INSTITUTIONS];
