-- AlterTable
ALTER TABLE `equipamento_catalogo` MODIFY `categoria` ENUM('CATEGORIA_0', 'CATEGORIA_4', 'CATEGORIA_3', 'CATEGORIA_2', 'CATEGORIA_1', 'ESPECIAL') NOT NULL DEFAULT 'CATEGORIA_0';

-- AlterTable
ALTER TABLE `inventario_item_base` ADD COLUMN `categoriaCalculada` ENUM('CATEGORIA_0', 'CATEGORIA_4', 'CATEGORIA_3', 'CATEGORIA_2', 'CATEGORIA_1', 'ESPECIAL') NOT NULL DEFAULT 'CATEGORIA_0',
    ADD COLUMN `espacosCalculados` INTEGER NOT NULL DEFAULT 1;

-- AlterTable
ALTER TABLE `inventario_item_campanha` ADD COLUMN `categoriaCalculada` ENUM('CATEGORIA_0', 'CATEGORIA_4', 'CATEGORIA_3', 'CATEGORIA_2', 'CATEGORIA_1', 'ESPECIAL') NOT NULL DEFAULT 'CATEGORIA_0';
