export declare const CAMPOS_MODIFICADOR_PERSONAGEM_CAMPANHA: readonly ["PV_MAX", "PE_MAX", "EA_MAX", "SAN_MAX", "DEFESA_BASE", "DEFESA_EQUIPAMENTO", "DEFESA_OUTROS", "ESQUIVA", "BLOQUEIO", "DESLOCAMENTO", "LIMITE_PE_EA_POR_TURNO", "PRESTIGIO_GERAL", "PRESTIGIO_CLA"];
export type CampoModificadorPersonagemCampanha = (typeof CAMPOS_MODIFICADOR_PERSONAGEM_CAMPANHA)[number];
