import { Prisma } from '@prisma/client';
import { PrismaService } from '../prisma/prisma.service';
type PrismaLike = PrismaService | Prisma.TransactionClient;
export declare class TecnicasAmaldicoadasPersistence {
    private readonly prisma;
    constructor(prisma: PrismaService);
    buscarTecnicaDetalhadaPorId(id: number, prisma?: PrismaLike): Promise<({
        suplemento: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string | null;
            status: import("@prisma/client").$Enums.StatusPublicacao;
            codigo: string;
            versao: string;
            icone: string | null;
            banner: string | null;
            tags: Prisma.JsonValue | null;
            autor: string | null;
        } | null;
        clas: ({
            cla: {
                id: number;
                nome: string;
                grandeCla: boolean;
            };
        } & {
            id: number;
            claId: number;
            tecnicaId: number;
        })[];
        habilidades: ({
            variacoes: {
                id: number;
                criadoEm: Date;
                atualizadoEm: Date;
                nome: string;
                descricao: string;
                requisitos: Prisma.JsonValue | null;
                ordem: number;
                criticoValor: number | null;
                criticoMultiplicador: number | null;
                alcance: string | null;
                execucao: import("@prisma/client").$Enums.TipoExecucao | null;
                area: import("@prisma/client").$Enums.AreaEfeito | null;
                alvo: string | null;
                duracao: string | null;
                resistencia: string | null;
                dtResistencia: string | null;
                custoPE: number | null;
                custoEA: number | null;
                custoSustentacaoEA: number | null;
                custoSustentacaoPE: number | null;
                danoFlat: number | null;
                danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
                dadosDano: Prisma.JsonValue | null;
                escalonaPorGrau: boolean | null;
                escalonamentoCustoEA: number | null;
                escalonamentoCustoPE: number | null;
                escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
                escalonamentoEfeito: Prisma.JsonValue | null;
                escalonamentoDano: Prisma.JsonValue | null;
                habilidadeTecnicaId: number;
                substituiCustos: boolean;
                efeitoAdicional: string | null;
            }[];
        } & {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: Prisma.JsonValue | null;
            codigo: string;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            efeito: string;
            tecnicaId: number;
            execucao: import("@prisma/client").$Enums.TipoExecucao;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number;
            custoEA: number;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            testesExigidos: Prisma.JsonValue | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: Prisma.JsonValue | null;
            escalonaPorGrau: boolean;
            grauTipoGrauCodigo: string | null;
            escalonamentoCustoEA: number;
            escalonamentoCustoPE: number;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
            escalonamentoEfeito: Prisma.JsonValue | null;
            escalonamentoDano: Prisma.JsonValue | null;
        })[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        fonte: import("@prisma/client").$Enums.TipoFonte;
        suplementoId: number | null;
        requisitos: Prisma.JsonValue | null;
        codigo: string;
        tipo: import("@prisma/client").$Enums.TipoTecnicaAmaldicoada;
        hereditaria: boolean;
        linkExterno: string | null;
    }) | null>;
    buscarTecnicaDetalhadaPorCodigo(codigo: string, prisma?: PrismaLike): Promise<({
        suplemento: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string | null;
            status: import("@prisma/client").$Enums.StatusPublicacao;
            codigo: string;
            versao: string;
            icone: string | null;
            banner: string | null;
            tags: Prisma.JsonValue | null;
            autor: string | null;
        } | null;
        clas: ({
            cla: {
                id: number;
                nome: string;
                grandeCla: boolean;
            };
        } & {
            id: number;
            claId: number;
            tecnicaId: number;
        })[];
        habilidades: ({
            variacoes: {
                id: number;
                criadoEm: Date;
                atualizadoEm: Date;
                nome: string;
                descricao: string;
                requisitos: Prisma.JsonValue | null;
                ordem: number;
                criticoValor: number | null;
                criticoMultiplicador: number | null;
                alcance: string | null;
                execucao: import("@prisma/client").$Enums.TipoExecucao | null;
                area: import("@prisma/client").$Enums.AreaEfeito | null;
                alvo: string | null;
                duracao: string | null;
                resistencia: string | null;
                dtResistencia: string | null;
                custoPE: number | null;
                custoEA: number | null;
                custoSustentacaoEA: number | null;
                custoSustentacaoPE: number | null;
                danoFlat: number | null;
                danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
                dadosDano: Prisma.JsonValue | null;
                escalonaPorGrau: boolean | null;
                escalonamentoCustoEA: number | null;
                escalonamentoCustoPE: number | null;
                escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
                escalonamentoEfeito: Prisma.JsonValue | null;
                escalonamentoDano: Prisma.JsonValue | null;
                habilidadeTecnicaId: number;
                substituiCustos: boolean;
                efeitoAdicional: string | null;
            }[];
        } & {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: Prisma.JsonValue | null;
            codigo: string;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            efeito: string;
            tecnicaId: number;
            execucao: import("@prisma/client").$Enums.TipoExecucao;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number;
            custoEA: number;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            testesExigidos: Prisma.JsonValue | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: Prisma.JsonValue | null;
            escalonaPorGrau: boolean;
            grauTipoGrauCodigo: string | null;
            escalonamentoCustoEA: number;
            escalonamentoCustoPE: number;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
            escalonamentoEfeito: Prisma.JsonValue | null;
            escalonamentoDano: Prisma.JsonValue | null;
        })[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        fonte: import("@prisma/client").$Enums.TipoFonte;
        suplementoId: number | null;
        requisitos: Prisma.JsonValue | null;
        codigo: string;
        tipo: import("@prisma/client").$Enums.TipoTecnicaAmaldicoada;
        hereditaria: boolean;
        linkExterno: string | null;
    }) | null>;
    listarTecnicasDetalhadas(where: Prisma.TecnicaAmaldicoadaWhereInput, orderBy?: Prisma.TecnicaAmaldicoadaOrderByWithRelationInput, prisma?: PrismaLike): Promise<({
        suplemento: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string | null;
            status: import("@prisma/client").$Enums.StatusPublicacao;
            codigo: string;
            versao: string;
            icone: string | null;
            banner: string | null;
            tags: Prisma.JsonValue | null;
            autor: string | null;
        } | null;
        clas: ({
            cla: {
                id: number;
                nome: string;
                grandeCla: boolean;
            };
        } & {
            id: number;
            claId: number;
            tecnicaId: number;
        })[];
        habilidades: ({
            variacoes: {
                id: number;
                criadoEm: Date;
                atualizadoEm: Date;
                nome: string;
                descricao: string;
                requisitos: Prisma.JsonValue | null;
                ordem: number;
                criticoValor: number | null;
                criticoMultiplicador: number | null;
                alcance: string | null;
                execucao: import("@prisma/client").$Enums.TipoExecucao | null;
                area: import("@prisma/client").$Enums.AreaEfeito | null;
                alvo: string | null;
                duracao: string | null;
                resistencia: string | null;
                dtResistencia: string | null;
                custoPE: number | null;
                custoEA: number | null;
                custoSustentacaoEA: number | null;
                custoSustentacaoPE: number | null;
                danoFlat: number | null;
                danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
                dadosDano: Prisma.JsonValue | null;
                escalonaPorGrau: boolean | null;
                escalonamentoCustoEA: number | null;
                escalonamentoCustoPE: number | null;
                escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
                escalonamentoEfeito: Prisma.JsonValue | null;
                escalonamentoDano: Prisma.JsonValue | null;
                habilidadeTecnicaId: number;
                substituiCustos: boolean;
                efeitoAdicional: string | null;
            }[];
        } & {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: Prisma.JsonValue | null;
            codigo: string;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            efeito: string;
            tecnicaId: number;
            execucao: import("@prisma/client").$Enums.TipoExecucao;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number;
            custoEA: number;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            testesExigidos: Prisma.JsonValue | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: Prisma.JsonValue | null;
            escalonaPorGrau: boolean;
            grauTipoGrauCodigo: string | null;
            escalonamentoCustoEA: number;
            escalonamentoCustoPE: number;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
            escalonamentoEfeito: Prisma.JsonValue | null;
            escalonamentoDano: Prisma.JsonValue | null;
        })[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        fonte: import("@prisma/client").$Enums.TipoFonte;
        suplementoId: number | null;
        requisitos: Prisma.JsonValue | null;
        codigo: string;
        tipo: import("@prisma/client").$Enums.TipoTecnicaAmaldicoada;
        hereditaria: boolean;
        linkExterno: string | null;
    })[]>;
    buscarTecnicasHereditariaPorCla(claId: number, prisma?: PrismaLike): Promise<({
        suplemento: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string | null;
            status: import("@prisma/client").$Enums.StatusPublicacao;
            codigo: string;
            versao: string;
            icone: string | null;
            banner: string | null;
            tags: Prisma.JsonValue | null;
            autor: string | null;
        } | null;
        clas: ({
            cla: {
                id: number;
                nome: string;
                grandeCla: boolean;
            };
        } & {
            id: number;
            claId: number;
            tecnicaId: number;
        })[];
        habilidades: ({
            variacoes: {
                id: number;
                criadoEm: Date;
                atualizadoEm: Date;
                nome: string;
                descricao: string;
                requisitos: Prisma.JsonValue | null;
                ordem: number;
                criticoValor: number | null;
                criticoMultiplicador: number | null;
                alcance: string | null;
                execucao: import("@prisma/client").$Enums.TipoExecucao | null;
                area: import("@prisma/client").$Enums.AreaEfeito | null;
                alvo: string | null;
                duracao: string | null;
                resistencia: string | null;
                dtResistencia: string | null;
                custoPE: number | null;
                custoEA: number | null;
                custoSustentacaoEA: number | null;
                custoSustentacaoPE: number | null;
                danoFlat: number | null;
                danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
                dadosDano: Prisma.JsonValue | null;
                escalonaPorGrau: boolean | null;
                escalonamentoCustoEA: number | null;
                escalonamentoCustoPE: number | null;
                escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
                escalonamentoEfeito: Prisma.JsonValue | null;
                escalonamentoDano: Prisma.JsonValue | null;
                habilidadeTecnicaId: number;
                substituiCustos: boolean;
                efeitoAdicional: string | null;
            }[];
        } & {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: Prisma.JsonValue | null;
            codigo: string;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            efeito: string;
            tecnicaId: number;
            execucao: import("@prisma/client").$Enums.TipoExecucao;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number;
            custoEA: number;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            testesExigidos: Prisma.JsonValue | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: Prisma.JsonValue | null;
            escalonaPorGrau: boolean;
            grauTipoGrauCodigo: string | null;
            escalonamentoCustoEA: number;
            escalonamentoCustoPE: number;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
            escalonamentoEfeito: Prisma.JsonValue | null;
            escalonamentoDano: Prisma.JsonValue | null;
        })[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        fonte: import("@prisma/client").$Enums.TipoFonte;
        suplementoId: number | null;
        requisitos: Prisma.JsonValue | null;
        codigo: string;
        tipo: import("@prisma/client").$Enums.TipoTecnicaAmaldicoada;
        hereditaria: boolean;
        linkExterno: string | null;
    })[]>;
    buscarTecnicaComUso(id: number, prisma?: PrismaLike): Promise<({
        _count: {
            personagensBaseComInata: number;
            personagensCampanhaComInata: number;
            personagensBaseAprendeu: number;
            personagensCampanhaAprendeu: number;
        };
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        fonte: import("@prisma/client").$Enums.TipoFonte;
        suplementoId: number | null;
        requisitos: Prisma.JsonValue | null;
        codigo: string;
        tipo: import("@prisma/client").$Enums.TipoTecnicaAmaldicoada;
        hereditaria: boolean;
        linkExterno: string | null;
    }) | null>;
}
export {};
