import { PrismaService } from '../prisma/prisma.service';
import { CreateVariacaoHabilidadeDto } from './dto/create-variacao.dto';
import { UpdateVariacaoHabilidadeDto } from './dto/update-variacao.dto';
export declare class TecnicasAmaldicoadasVariacoesService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    findAllVariacoes(habilidadeTecnicaId: number): Promise<{
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        execucao: import("@prisma/client").$Enums.TipoExecucao | null;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number | null;
        custoEA: number | null;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean | null;
        escalonamentoCustoEA: number | null;
        escalonamentoCustoPE: number | null;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
        habilidadeTecnicaId: number;
        substituiCustos: boolean;
        efeitoAdicional: string | null;
    }[]>;
    findOneVariacao(id: number): Promise<{
        habilidadeTecnica: {
            id: number;
            nome: string;
            codigo: string;
            tecnica: {
                id: number;
                nome: string;
                codigo: string;
            };
        };
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        execucao: import("@prisma/client").$Enums.TipoExecucao | null;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number | null;
        custoEA: number | null;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean | null;
        escalonamentoCustoEA: number | null;
        escalonamentoCustoPE: number | null;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
        habilidadeTecnicaId: number;
        substituiCustos: boolean;
        efeitoAdicional: string | null;
    }>;
    createVariacao(dto: CreateVariacaoHabilidadeDto): Promise<{
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        execucao: import("@prisma/client").$Enums.TipoExecucao | null;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number | null;
        custoEA: number | null;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean | null;
        escalonamentoCustoEA: number | null;
        escalonamentoCustoPE: number | null;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
        habilidadeTecnicaId: number;
        substituiCustos: boolean;
        efeitoAdicional: string | null;
    }>;
    updateVariacao(id: number, dto: UpdateVariacaoHabilidadeDto): Promise<{
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        execucao: import("@prisma/client").$Enums.TipoExecucao | null;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number | null;
        custoEA: number | null;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean | null;
        escalonamentoCustoEA: number | null;
        escalonamentoCustoPE: number | null;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
        habilidadeTecnicaId: number;
        substituiCustos: boolean;
        efeitoAdicional: string | null;
    }>;
    removeVariacao(id: number): Promise<void>;
}
