import { PrismaService } from '../prisma/prisma.service';
import { CreateHabilidadeTecnicaDto } from './dto/create-habilidade-tecnica.dto';
import { UpdateHabilidadeTecnicaDto } from './dto/update-habilidade-tecnica.dto';
export declare class TecnicasAmaldicoadasHabilidadesService {
    private readonly prisma;
    constructor(prisma: PrismaService);
    findAllHabilidades(tecnicaId: number): Promise<({
        variacoes: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: import("@prisma/client/runtime/library").JsonValue | null;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            execucao: import("@prisma/client").$Enums.TipoExecucao | null;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number | null;
            custoEA: number | null;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
            escalonaPorGrau: boolean | null;
            escalonamentoCustoEA: number | null;
            escalonamentoCustoPE: number | null;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
            escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
            escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
            habilidadeTecnicaId: number;
            substituiCustos: boolean;
            efeitoAdicional: string | null;
        }[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        codigo: string;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        efeito: string;
        tecnicaId: number;
        execucao: import("@prisma/client").$Enums.TipoExecucao;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number;
        custoEA: number;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        testesExigidos: import("@prisma/client/runtime/library").JsonValue | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean;
        grauTipoGrauCodigo: string | null;
        escalonamentoCustoEA: number;
        escalonamentoCustoPE: number;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
    })[]>;
    findOneHabilidade(id: number): Promise<{
        tecnica: {
            id: number;
            nome: string;
            codigo: string;
        };
        variacoes: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: import("@prisma/client/runtime/library").JsonValue | null;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            execucao: import("@prisma/client").$Enums.TipoExecucao | null;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number | null;
            custoEA: number | null;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
            escalonaPorGrau: boolean | null;
            escalonamentoCustoEA: number | null;
            escalonamentoCustoPE: number | null;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
            escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
            escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
            habilidadeTecnicaId: number;
            substituiCustos: boolean;
            efeitoAdicional: string | null;
        }[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        codigo: string;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        efeito: string;
        tecnicaId: number;
        execucao: import("@prisma/client").$Enums.TipoExecucao;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number;
        custoEA: number;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        testesExigidos: import("@prisma/client/runtime/library").JsonValue | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean;
        grauTipoGrauCodigo: string | null;
        escalonamentoCustoEA: number;
        escalonamentoCustoPE: number;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    createHabilidade(dto: CreateHabilidadeTecnicaDto): Promise<{
        variacoes: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: import("@prisma/client/runtime/library").JsonValue | null;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            execucao: import("@prisma/client").$Enums.TipoExecucao | null;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number | null;
            custoEA: number | null;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
            escalonaPorGrau: boolean | null;
            escalonamentoCustoEA: number | null;
            escalonamentoCustoPE: number | null;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
            escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
            escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
            habilidadeTecnicaId: number;
            substituiCustos: boolean;
            efeitoAdicional: string | null;
        }[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        codigo: string;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        efeito: string;
        tecnicaId: number;
        execucao: import("@prisma/client").$Enums.TipoExecucao;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number;
        custoEA: number;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        testesExigidos: import("@prisma/client/runtime/library").JsonValue | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean;
        grauTipoGrauCodigo: string | null;
        escalonamentoCustoEA: number;
        escalonamentoCustoPE: number;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    updateHabilidade(id: number, dto: UpdateHabilidadeTecnicaDto): Promise<{
        variacoes: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: import("@prisma/client/runtime/library").JsonValue | null;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            execucao: import("@prisma/client").$Enums.TipoExecucao | null;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number | null;
            custoEA: number | null;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
            escalonaPorGrau: boolean | null;
            escalonamentoCustoEA: number | null;
            escalonamentoCustoPE: number | null;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
            escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
            escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
            habilidadeTecnicaId: number;
            substituiCustos: boolean;
            efeitoAdicional: string | null;
        }[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        codigo: string;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        efeito: string;
        tecnicaId: number;
        execucao: import("@prisma/client").$Enums.TipoExecucao;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number;
        custoEA: number;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        testesExigidos: import("@prisma/client/runtime/library").JsonValue | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean;
        grauTipoGrauCodigo: string | null;
        escalonamentoCustoEA: number;
        escalonamentoCustoPE: number;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    removeHabilidade(id: number): Promise<void>;
}
