import { CreateTecnicaDto } from './dto/create-tecnica.dto';
import { UpdateTecnicaDto } from './dto/update-tecnica.dto';
import { FiltrarTecnicasDto } from './dto/filtrar-tecnicas.dto';
import { TecnicaDetalhadaDto } from './dto/tecnica-detalhada.dto';
import { ExportarTecnicasJsonDto } from './dto/exportar-tecnicas-json.dto';
import { ImportarTecnicasJsonDto } from './dto/importar-tecnicas-json.dto';
import { CreateHabilidadeTecnicaDto } from './dto/create-habilidade-tecnica.dto';
import { UpdateHabilidadeTecnicaDto } from './dto/update-habilidade-tecnica.dto';
import { CreateVariacaoHabilidadeDto } from './dto/create-variacao.dto';
import { UpdateVariacaoHabilidadeDto } from './dto/update-variacao.dto';
import { ImportacaoTecnicasResumo, RegistroJson } from './engine/tecnicas-amaldicoadas.engine.types';
import { TecnicasAmaldicoadasCrudService } from './tecnicas-amaldicoadas.crud.service';
import { TecnicasAmaldicoadasImportExportService } from './tecnicas-amaldicoadas.import-export.service';
import { TecnicasAmaldicoadasHabilidadesService } from './tecnicas-amaldicoadas.habilidades.service';
import { TecnicasAmaldicoadasVariacoesService } from './tecnicas-amaldicoadas.variacoes.service';
export declare class TecnicasAmaldicoadasService {
    private readonly crudService;
    private readonly importExportService;
    private readonly habilidadesService;
    private readonly variacoesService;
    constructor(crudService: TecnicasAmaldicoadasCrudService, importExportService: TecnicasAmaldicoadasImportExportService, habilidadesService: TecnicasAmaldicoadasHabilidadesService, variacoesService: TecnicasAmaldicoadasVariacoesService);
    getGuiaImportacaoJson(): RegistroJson;
    exportarTecnicasJson(query: ExportarTecnicasJsonDto): Promise<RegistroJson>;
    importarTecnicasJson(dto: ImportarTecnicasJsonDto): Promise<ImportacaoTecnicasResumo>;
    findAllTecnicas(filtros: FiltrarTecnicasDto): Promise<TecnicaDetalhadaDto[]>;
    findOneTecnica(id: number): Promise<TecnicaDetalhadaDto>;
    findTecnicaByCodigo(codigo: string): Promise<TecnicaDetalhadaDto>;
    createTecnica(dto: CreateTecnicaDto): Promise<TecnicaDetalhadaDto>;
    updateTecnica(id: number, dto: UpdateTecnicaDto): Promise<TecnicaDetalhadaDto>;
    removeTecnica(id: number): Promise<void>;
    findTecnicasByCla(claId: number): Promise<TecnicaDetalhadaDto[]>;
    findAllHabilidades(tecnicaId: number): Promise<({
        variacoes: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: import("@prisma/client/runtime/library").JsonValue | null;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            execucao: import("@prisma/client").$Enums.TipoExecucao | null;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number | null;
            custoEA: number | null;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
            escalonaPorGrau: boolean | null;
            escalonamentoCustoEA: number | null;
            escalonamentoCustoPE: number | null;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
            escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
            escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
            habilidadeTecnicaId: number;
            substituiCustos: boolean;
            efeitoAdicional: string | null;
        }[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        codigo: string;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        efeito: string;
        tecnicaId: number;
        execucao: import("@prisma/client").$Enums.TipoExecucao;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number;
        custoEA: number;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        testesExigidos: import("@prisma/client/runtime/library").JsonValue | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean;
        grauTipoGrauCodigo: string | null;
        escalonamentoCustoEA: number;
        escalonamentoCustoPE: number;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
    })[]>;
    findOneHabilidade(id: number): Promise<{
        tecnica: {
            id: number;
            nome: string;
            codigo: string;
        };
        variacoes: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: import("@prisma/client/runtime/library").JsonValue | null;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            execucao: import("@prisma/client").$Enums.TipoExecucao | null;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number | null;
            custoEA: number | null;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
            escalonaPorGrau: boolean | null;
            escalonamentoCustoEA: number | null;
            escalonamentoCustoPE: number | null;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
            escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
            escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
            habilidadeTecnicaId: number;
            substituiCustos: boolean;
            efeitoAdicional: string | null;
        }[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        codigo: string;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        efeito: string;
        tecnicaId: number;
        execucao: import("@prisma/client").$Enums.TipoExecucao;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number;
        custoEA: number;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        testesExigidos: import("@prisma/client/runtime/library").JsonValue | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean;
        grauTipoGrauCodigo: string | null;
        escalonamentoCustoEA: number;
        escalonamentoCustoPE: number;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    createHabilidade(dto: CreateHabilidadeTecnicaDto): Promise<{
        variacoes: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: import("@prisma/client/runtime/library").JsonValue | null;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            execucao: import("@prisma/client").$Enums.TipoExecucao | null;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number | null;
            custoEA: number | null;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
            escalonaPorGrau: boolean | null;
            escalonamentoCustoEA: number | null;
            escalonamentoCustoPE: number | null;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
            escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
            escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
            habilidadeTecnicaId: number;
            substituiCustos: boolean;
            efeitoAdicional: string | null;
        }[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        codigo: string;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        efeito: string;
        tecnicaId: number;
        execucao: import("@prisma/client").$Enums.TipoExecucao;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number;
        custoEA: number;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        testesExigidos: import("@prisma/client/runtime/library").JsonValue | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean;
        grauTipoGrauCodigo: string | null;
        escalonamentoCustoEA: number;
        escalonamentoCustoPE: number;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    updateHabilidade(id: number, dto: UpdateHabilidadeTecnicaDto): Promise<{
        variacoes: {
            id: number;
            criadoEm: Date;
            atualizadoEm: Date;
            nome: string;
            descricao: string;
            requisitos: import("@prisma/client/runtime/library").JsonValue | null;
            ordem: number;
            criticoValor: number | null;
            criticoMultiplicador: number | null;
            alcance: string | null;
            execucao: import("@prisma/client").$Enums.TipoExecucao | null;
            area: import("@prisma/client").$Enums.AreaEfeito | null;
            alvo: string | null;
            duracao: string | null;
            resistencia: string | null;
            dtResistencia: string | null;
            custoPE: number | null;
            custoEA: number | null;
            custoSustentacaoEA: number | null;
            custoSustentacaoPE: number | null;
            danoFlat: number | null;
            danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
            dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
            escalonaPorGrau: boolean | null;
            escalonamentoCustoEA: number | null;
            escalonamentoCustoPE: number | null;
            escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
            escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
            escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
            habilidadeTecnicaId: number;
            substituiCustos: boolean;
            efeitoAdicional: string | null;
        }[];
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        codigo: string;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        efeito: string;
        tecnicaId: number;
        execucao: import("@prisma/client").$Enums.TipoExecucao;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number;
        custoEA: number;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        testesExigidos: import("@prisma/client/runtime/library").JsonValue | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean;
        grauTipoGrauCodigo: string | null;
        escalonamentoCustoEA: number;
        escalonamentoCustoPE: number;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
    }>;
    removeHabilidade(id: number): Promise<void>;
    findAllVariacoes(habilidadeTecnicaId: number): Promise<{
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        execucao: import("@prisma/client").$Enums.TipoExecucao | null;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number | null;
        custoEA: number | null;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean | null;
        escalonamentoCustoEA: number | null;
        escalonamentoCustoPE: number | null;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
        habilidadeTecnicaId: number;
        substituiCustos: boolean;
        efeitoAdicional: string | null;
    }[]>;
    findOneVariacao(id: number): Promise<{
        habilidadeTecnica: {
            id: number;
            nome: string;
            codigo: string;
            tecnica: {
                id: number;
                nome: string;
                codigo: string;
            };
        };
    } & {
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        execucao: import("@prisma/client").$Enums.TipoExecucao | null;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number | null;
        custoEA: number | null;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean | null;
        escalonamentoCustoEA: number | null;
        escalonamentoCustoPE: number | null;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
        habilidadeTecnicaId: number;
        substituiCustos: boolean;
        efeitoAdicional: string | null;
    }>;
    createVariacao(dto: CreateVariacaoHabilidadeDto): Promise<{
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        execucao: import("@prisma/client").$Enums.TipoExecucao | null;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number | null;
        custoEA: number | null;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean | null;
        escalonamentoCustoEA: number | null;
        escalonamentoCustoPE: number | null;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
        habilidadeTecnicaId: number;
        substituiCustos: boolean;
        efeitoAdicional: string | null;
    }>;
    updateVariacao(id: number, dto: UpdateVariacaoHabilidadeDto): Promise<{
        id: number;
        criadoEm: Date;
        atualizadoEm: Date;
        nome: string;
        descricao: string;
        requisitos: import("@prisma/client/runtime/library").JsonValue | null;
        ordem: number;
        criticoValor: number | null;
        criticoMultiplicador: number | null;
        alcance: string | null;
        execucao: import("@prisma/client").$Enums.TipoExecucao | null;
        area: import("@prisma/client").$Enums.AreaEfeito | null;
        alvo: string | null;
        duracao: string | null;
        resistencia: string | null;
        dtResistencia: string | null;
        custoPE: number | null;
        custoEA: number | null;
        custoSustentacaoEA: number | null;
        custoSustentacaoPE: number | null;
        danoFlat: number | null;
        danoFlatTipo: import("@prisma/client").$Enums.TipoDano | null;
        dadosDano: import("@prisma/client/runtime/library").JsonValue | null;
        escalonaPorGrau: boolean | null;
        escalonamentoCustoEA: number | null;
        escalonamentoCustoPE: number | null;
        escalonamentoTipo: import("@prisma/client").$Enums.TipoEscalonamentoHabilidade | null;
        escalonamentoEfeito: import("@prisma/client/runtime/library").JsonValue | null;
        escalonamentoDano: import("@prisma/client/runtime/library").JsonValue | null;
        habilidadeTecnicaId: number;
        substituiCustos: boolean;
        efeitoAdicional: string | null;
    }>;
    removeVariacao(id: number): Promise<void>;
}
