CREATE TABLE IF NOT EXISTS `DominioSessao` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `sessaoId` INTEGER NOT NULL,
  `cenaId` INTEGER NOT NULL,
  `personagemSessaoId` INTEGER NULL,
  `npcSessaoId` INTEGER NULL,
  `habilidadeTecnicaId` INTEGER NULL,
  `nome` VARCHAR(160) NOT NULL,
  `descricaoAcertoGarantido` TEXT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'ABRINDO',
  `acertoGarantidoAtivo` BOOLEAN NOT NULL DEFAULT true,
  `grauBarreira` INTEGER NOT NULL DEFAULT 2,
  `integridadeMax` INTEGER NULL,
  `integridadeAtual` INTEGER NULL,
  `rupturas` INTEGER NOT NULL DEFAULT 0,
  `exteriorReforcado` BOOLEAN NOT NULL DEFAULT false,
  `instavel` BOOLEAN NOT NULL DEFAULT false,
  `investimentoIntegridade` INTEGER NOT NULL DEFAULT 0,
  `rodadaAbertura` INTEGER NOT NULL,
  `rodadaUltimaPressao` INTEGER NULL,
  `sustentacaoHabilidadeId` INTEGER NULL,
  `criadoPorUsuarioId` INTEGER NOT NULL,
  `criadoEm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `encerradoEm` DATETIME(3) NULL,
  `encerradoPorUsuarioId` INTEGER NULL,
  `motivoEncerramento` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `DominioSessao_sessaoId_cenaId_estado_idx` (`sessaoId`, `cenaId`, `estado`),
  INDEX `DominioSessao_personagemSessaoId_estado_idx` (`personagemSessaoId`, `estado`),
  INDEX `DominioSessao_npcSessaoId_estado_idx` (`npcSessaoId`, `estado`),
  INDEX `DominioSessao_sustentacaoHabilidadeId_idx` (`sustentacaoHabilidadeId`),
  CONSTRAINT `DominioSessao_sessaoId_fkey` FOREIGN KEY (`sessaoId`) REFERENCES `Sessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DominioSessao_cenaId_fkey` FOREIGN KEY (`cenaId`) REFERENCES `Cena`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DominioSessao_personagemSessaoId_fkey` FOREIGN KEY (`personagemSessaoId`) REFERENCES `PersonagemSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DominioSessao_npcSessaoId_fkey` FOREIGN KEY (`npcSessaoId`) REFERENCES `NpcAmeacaSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DominioSessao_habilidadeTecnicaId_fkey` FOREIGN KEY (`habilidadeTecnicaId`) REFERENCES `habilidade_tecnica`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `DominioSessao_sustentacaoHabilidadeId_fkey` FOREIGN KEY (`sustentacaoHabilidadeId`) REFERENCES `PersonagemSessaoHabilidadeSustentada`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `DominioSessaoAlvo` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `dominioSessaoId` INTEGER NOT NULL,
  `personagemSessaoId` INTEGER NULL,
  `npcSessaoId` INTEGER NULL,
  PRIMARY KEY (`id`),
  INDEX `DominioSessaoAlvo_dominioSessaoId_idx` (`dominioSessaoId`),
  INDEX `DominioSessaoAlvo_personagemSessaoId_idx` (`personagemSessaoId`),
  INDEX `DominioSessaoAlvo_npcSessaoId_idx` (`npcSessaoId`),
  CONSTRAINT `DominioSessaoAlvo_dominioSessaoId_fkey` FOREIGN KEY (`dominioSessaoId`) REFERENCES `DominioSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DominioSessaoAlvo_personagemSessaoId_fkey` FOREIGN KEY (`personagemSessaoId`) REFERENCES `PersonagemSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DominioSessaoAlvo_npcSessaoId_fkey` FOREIGN KEY (`npcSessaoId`) REFERENCES `NpcAmeacaSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `DisputaDominioSessao` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `sessaoId` INTEGER NOT NULL,
  `cenaId` INTEGER NOT NULL,
  `estado` VARCHAR(20) NOT NULL DEFAULT 'ATIVA',
  `resolucoesConcluidas` INTEGER NOT NULL DEFAULT 0,
  `rodadaProximaResolucao` INTEGER NOT NULL,
  `criadoPorUsuarioId` INTEGER NOT NULL,
  `criadoEm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `encerradaEm` DATETIME(3) NULL,
  `motivoEncerramento` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `DisputaDominioSessao_sessaoId_cenaId_estado_idx` (`sessaoId`, `cenaId`, `estado`),
  CONSTRAINT `DisputaDominioSessao_sessaoId_fkey` FOREIGN KEY (`sessaoId`) REFERENCES `Sessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DisputaDominioSessao_cenaId_fkey` FOREIGN KEY (`cenaId`) REFERENCES `Cena`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `DisputaDominioParticipante` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `disputaDominioSessaoId` INTEGER NOT NULL,
  `dominioSessaoId` INTEGER NOT NULL,
  `dominancia` INTEGER NOT NULL DEFAULT 0,
  `entradaTardia` BOOLEAN NOT NULL DEFAULT false,
  `expansaoReativa` BOOLEAN NOT NULL DEFAULT false,
  `primeiraResolucaoPendente` BOOLEAN NOT NULL DEFAULT false,
  `refinado` BOOLEAN NOT NULL DEFAULT false,
  `forcarNaRodada` INTEGER NULL,
  `pressionarDominioSessaoId` INTEGER NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `disputa_dominio_participante_unico` (`disputaDominioSessaoId`, `dominioSessaoId`),
  INDEX `DisputaDominioParticipante_dominioSessaoId_idx` (`dominioSessaoId`),
  CONSTRAINT `DisputaDominioParticipante_disputaDominioSessaoId_fkey` FOREIGN KEY (`disputaDominioSessaoId`) REFERENCES `DisputaDominioSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DisputaDominioParticipante_dominioSessaoId_fkey` FOREIGN KEY (`dominioSessaoId`) REFERENCES `DominioSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `DisputaDominioAlvo` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `disputaDominioSessaoId` INTEGER NOT NULL,
  `personagemSessaoId` INTEGER NULL,
  `npcSessaoId` INTEGER NULL,
  PRIMARY KEY (`id`),
  INDEX `DisputaDominioAlvo_disputaDominioSessaoId_idx` (`disputaDominioSessaoId`),
  INDEX `DisputaDominioAlvo_personagemSessaoId_idx` (`personagemSessaoId`),
  INDEX `DisputaDominioAlvo_npcSessaoId_idx` (`npcSessaoId`),
  CONSTRAINT `DisputaDominioAlvo_disputaDominioSessaoId_fkey` FOREIGN KEY (`disputaDominioSessaoId`) REFERENCES `DisputaDominioSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DisputaDominioAlvo_personagemSessaoId_fkey` FOREIGN KEY (`personagemSessaoId`) REFERENCES `PersonagemSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DisputaDominioAlvo_npcSessaoId_fkey` FOREIGN KEY (`npcSessaoId`) REFERENCES `NpcAmeacaSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE IF NOT EXISTS `DefesaAntiDominioSessao` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `sessaoId` INTEGER NOT NULL,
  `cenaId` INTEGER NOT NULL,
  `personagemSessaoId` INTEGER NULL,
  `npcSessaoId` INTEGER NULL,
  `habilidadeTecnicaId` INTEGER NULL,
  `tipo` VARCHAR(24) NOT NULL,
  `integridadeMax` INTEGER NULL,
  `integridadeAtual` INTEGER NULL,
  `pesEnraizados` BOOLEAN NOT NULL DEFAULT false,
  `variacao` VARCHAR(80) NULL,
  `ativa` BOOLEAN NOT NULL DEFAULT true,
  `sustentacaoHabilidadeId` INTEGER NULL,
  `criadoPorUsuarioId` INTEGER NOT NULL,
  `criadoEm` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `encerradaEm` DATETIME(3) NULL,
  `motivoEncerramento` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `DefesaAntiDominioSessao_sessaoId_cenaId_ativa_idx` (`sessaoId`, `cenaId`, `ativa`),
  INDEX `DefesaAntiDominioSessao_personagemSessaoId_ativa_idx` (`personagemSessaoId`, `ativa`),
  INDEX `DefesaAntiDominioSessao_npcSessaoId_ativa_idx` (`npcSessaoId`, `ativa`),
  INDEX `DefesaAntiDominioSessao_sustentacaoHabilidadeId_idx` (`sustentacaoHabilidadeId`),
  CONSTRAINT `DefesaAntiDominioSessao_sessaoId_fkey` FOREIGN KEY (`sessaoId`) REFERENCES `Sessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DefesaAntiDominioSessao_cenaId_fkey` FOREIGN KEY (`cenaId`) REFERENCES `Cena`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DefesaAntiDominioSessao_personagemSessaoId_fkey` FOREIGN KEY (`personagemSessaoId`) REFERENCES `PersonagemSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DefesaAntiDominioSessao_npcSessaoId_fkey` FOREIGN KEY (`npcSessaoId`) REFERENCES `NpcAmeacaSessao`(`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `DefesaAntiDominioSessao_habilidadeTecnicaId_fkey` FOREIGN KEY (`habilidadeTecnicaId`) REFERENCES `habilidade_tecnica`(`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `DefesaAntiDominioSessao_sustentacaoHabilidadeId_fkey` FOREIGN KEY (`sustentacaoHabilidadeId`) REFERENCES `PersonagemSessaoHabilidadeSustentada`(`id`) ON DELETE SET NULL ON UPDATE CASCADE
);
