export type CondicaoPadrao = {
  nome: string;
  descricao: string;
};

export const CONDICOES_PADRAO: CondicaoPadrao[] = [
  { nome: 'Abalado', descricao: 'Sofre -1d20 em testes; se receber de novo, evolui para Apavorado.' },
  { nome: 'Agarrado', descricao: 'Fica desprevenido e imovel, com penalidade em ataques e mobilidade.' },
  { nome: 'Alquebrado', descricao: 'O custo em PE de habilidades e rituais aumenta em +1.' },
  { nome: 'Apavorado', descricao: 'Sofre -2d20 em pericias e precisa fugir da fonte do medo.' },
  { nome: 'Asfixiado', descricao: 'Nao consegue respirar; pode cair inconsciente e perder PV por rodada.' },
  { nome: 'Atordoado', descricao: 'Fica desprevenido e nao pode realizar acoes.' },
  { nome: 'Caido', descricao: 'No chao, com deslocamento reduzido e modificadores de ataque/defesa.' },
  { nome: 'Cego', descricao: 'Fica desprevenido e lento, com forte penalidade em percepcao e ataques.' },
  { nome: 'Confuso', descricao: 'Comportamento aleatorio por rodada, podendo atacar aliados ou ficar inerte.' },
  { nome: 'Debilitado', descricao: 'Sofre -2d20 em Agilidade, Forca e Vigor; pode evoluir para inconsciente.' },
  { nome: 'Desprevenido', descricao: 'Sofre -5 na Defesa e -1d20 em Reflexos.' },
  { nome: 'Doente', descricao: 'Sob efeito de uma doenca especifica.' },
  { nome: 'Em Chamas', descricao: 'Sofre dano de fogo no inicio do turno ate apagar as chamas.' },
  { nome: 'Enjoado', descricao: 'Pode fazer apenas acao padrao ou de movimento por rodada.' },
  { nome: 'Enlouquecendo', descricao: 'Em risco de insanidade permanente se iniciar turnos suficientes nessa condicao.' },
  { nome: 'Enredado', descricao: 'Fica lento, vulneravel e com penalidade em testes de ataque.' },
  { nome: 'Envenenado', descricao: 'Efeito depende do veneno; pode causar condicoes ou dano recorrente.' },
  { nome: 'Esmorecido', descricao: 'Sofre -2d20 em testes de Intelecto e Presenca.' },
  { nome: 'Exausto', descricao: 'Fica Debilitado, Lento e Vulneravel; pode evoluir para inconsciente.' },
  { nome: 'Fascinado', descricao: 'A atencao fica presa em um foco e o personagem nao consegue agir normalmente.' },
  { nome: 'Fatigado', descricao: 'Fica Fraco e Vulneravel; se repetir, evolui para Exausto.' },
  { nome: 'Fraco', descricao: 'Sofre -1d20 em testes de Agilidade, Forca e Vigor.' },
  { nome: 'Frustrado', descricao: 'Sofre -1d20 em testes de Intelecto e Presenca.' },
  { nome: 'Imovel', descricao: 'Todas as formas de deslocamento vao para 0m.' },
  { nome: 'Inconsciente', descricao: 'Fica indefeso e sem acoes ou reacoes.' },
  { nome: 'Indefeso', descricao: 'Defesa -10, falha em Reflexos e fica vulneravel a golpe de misericordia.' },
  { nome: 'Lento', descricao: 'Deslocamento reduzido a metade; nao pode correr nem investir.' },
  { nome: 'Machucado', descricao: 'Indica que o alvo esta com metade ou menos dos PV totais.' },
  { nome: 'Morrendo', descricao: 'Com 0 PV, pode morrer apos iniciar turnos suficientes nessa condicao.' },
  { nome: 'Ofuscado', descricao: 'Sofre -1d20 em testes de ataque e de Percepcao.' },
  { nome: 'Paralisado', descricao: 'Fica imovel e indefeso, podendo apenas acoes puramente mentais.' },
  { nome: 'Pasmo', descricao: 'Nao pode realizar acoes.' },
  { nome: 'Perturbado', descricao: 'Quando ocorre pela primeira vez na cena, gera efeito de insanidade.' },
  { nome: 'Petrificado', descricao: 'Fica inconsciente e recebe resistencia a dano 10.' },
  { nome: 'Sangrando', descricao: 'Perde PV por turno ate estabilizar por Vigor ou Medicina.' },
  { nome: 'Silenciado', descricao: 'Nao pode usar habilidades que exigem fala/encantamento.' },
  { nome: 'Surdo', descricao: 'Nao percebe por audio e sofre penalidade em Iniciativa.' },
  { nome: 'Surpreendido', descricao: 'Fica desprevenido e nao pode agir ao ser pego sem preparo.' },
  { nome: 'Vulneravel', descricao: 'Sofre -2 na Defesa.' },
  { nome: 'Insano', descricao: 'Estado de insanidade consolidada apos colapso mental.' },
  { nome: 'Morto', descricao: 'Estado final de morte do personagem.' },
];
