-- AlterTable
ALTER TABLE `personagembase` ADD COLUMN `defesa` INTEGER NOT NULL DEFAULT 10,
    ADD COLUMN `deslocamento` INTEGER NOT NULL DEFAULT 9,
    ADD COLUMN `eaMaximo` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `limitePeEaPorTurno` INTEGER NOT NULL DEFAULT 1,
    ADD COLUMN `peMaximo` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `pvMaximo` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `reacoesBasePorTurno` INTEGER NOT NULL DEFAULT 2,
    ADD COLUMN `sanMaximo` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `turnosEnlouquecendo` INTEGER NOT NULL DEFAULT 3,
    ADD COLUMN `turnosMorrendo` INTEGER NOT NULL DEFAULT 3;
