export const landingImages = {
  heroGif: '/images/landing/effects/hollow-purple.gif',
  heroWatermark: '/images/landing/branding/simbolo-escola.png',
  aboutYouth: '/images/landing/backgrounds/trio-gojo-jovem.png',
  featuresSchool: '/images/landing/backgrounds/escola-tecnica-jujutsu.png',
  villains: '/images/landing/backgrounds/maldicoes-desastres.png',
  ctaGif: '/images/landing/effects/malevolent-shrine.gif',
  classFeiticeiro: '/images/landing/characters/gojo-art.jpg',
  classUsuario: '/images/landing/characters/mahito-art.jpg',
  classEspirito: '/images/landing/backgrounds/maldicoes-desastres.png',
  classCelestial: '/images/landing/characters/choso-art.jpg',
  classCombatente: '/images/landing/classes/combatente.png',
  classSentinela: '/images/landing/classes/sentinela.png',
  classEspecialista: '/images/landing/classes/especialista.png',
  logoJjkJapones: '/images/landing/branding/logo-jjk-japones.png',
  simboloEscola: '/images/landing/branding/simbolo-escola.png',
} as const;
